// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdEIc0jBzkiQdMttjsIkaHoHhBef7jcmE',
    appId: '1:699300120797:web:6e21ce6c6551d0ffcb7334',
    messagingSenderId: '699300120797',
    projectId: 'musicapp-16092',
    authDomain: 'musicapp-16092.firebaseapp.com',
    storageBucket: 'musicapp-16092.appspot.com',
    measurementId: 'G-QWK81GPM0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnrzMGjrgSUigC67BCQqDUcIG2XmDtDSA',
    appId: '1:699300120797:android:279e12d2b9671bcbcb7334',
    messagingSenderId: '699300120797',
    projectId: 'musicapp-16092',
    storageBucket: 'musicapp-16092.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc0sA7MmtbwQDTVT6PS1H0JJ2i6RA9oYc',
    appId: '1:699300120797:ios:0313e7a7aff9b4f9cb7334',
    messagingSenderId: '699300120797',
    projectId: 'musicapp-16092',
    storageBucket: 'musicapp-16092.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc0sA7MmtbwQDTVT6PS1H0JJ2i6RA9oYc',
    appId: '1:699300120797:ios:0313e7a7aff9b4f9cb7334',
    messagingSenderId: '699300120797',
    projectId: 'musicapp-16092',
    storageBucket: 'musicapp-16092.appspot.com',
    iosBundleId: 'com.example.test',
  );
}
